version: 2

jobs:
  build:
    docker:
      - image: nixos/nix
    # Required because hc package default DNA name is working directory name
    working_directory: ~/learning-pathways
    steps:
      - checkout

      # note: as of 1 Feb 2020, we could instead use:
      # nix-shell https://holochain.love
      # but here we lock it to a holonix release so that it will continue to work as love evolves:
      - run: |
          nix-shell https://github.com/holochain/holonix/archive/v0.0.65.tar.gz \
            --option substituters 'https://cache.holo.host https://cache.nixos.org' \
            --option trusted-public-keys \
              'cache.holo.host-1:lNXIXtJgS9Iuw4Cu6X0HINLu9sTfcjEntnrgwMQIMcE=
               cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=' \
            --run 'hc test'
